// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protocol.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Vector struct {
	X                    float32  `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    float32  `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	Z                    float32  `protobuf:"fixed32,3,opt,name=z,proto3" json:"z,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Vector) Reset()         { *m = Vector{} }
func (m *Vector) String() string { return proto.CompactTextString(m) }
func (*Vector) ProtoMessage()    {}
func (*Vector) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_6fd95a7833d73444, []int{0}
}
func (m *Vector) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Vector.Unmarshal(m, b)
}
func (m *Vector) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Vector.Marshal(b, m, deterministic)
}
func (dst *Vector) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Vector.Merge(dst, src)
}
func (m *Vector) XXX_Size() int {
	return xxx_messageInfo_Vector.Size(m)
}
func (m *Vector) XXX_DiscardUnknown() {
	xxx_messageInfo_Vector.DiscardUnknown(m)
}

var xxx_messageInfo_Vector proto.InternalMessageInfo

func (m *Vector) GetX() float32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Vector) GetY() float32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *Vector) GetZ() float32 {
	if m != nil {
		return m.Z
	}
	return 0
}

type Connection struct {
	ConnectedTo          string   `protobuf:"bytes,1,opt,name=connected_to,json=connectedTo,proto3" json:"connected_to,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Connection) Reset()         { *m = Connection{} }
func (m *Connection) String() string { return proto.CompactTextString(m) }
func (*Connection) ProtoMessage()    {}
func (*Connection) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_6fd95a7833d73444, []int{1}
}
func (m *Connection) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Connection.Unmarshal(m, b)
}
func (m *Connection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Connection.Marshal(b, m, deterministic)
}
func (dst *Connection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Connection.Merge(dst, src)
}
func (m *Connection) XXX_Size() int {
	return xxx_messageInfo_Connection.Size(m)
}
func (m *Connection) XXX_DiscardUnknown() {
	xxx_messageInfo_Connection.DiscardUnknown(m)
}

var xxx_messageInfo_Connection proto.InternalMessageInfo

func (m *Connection) GetConnectedTo() string {
	if m != nil {
		return m.ConnectedTo
	}
	return ""
}

type Cell struct {
	Id                   string        `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	EnergyLevel          uint64        `protobuf:"varint,2,opt,name=energy_level,json=energyLevel,proto3" json:"energy_level,omitempty"`
	Pos                  *Vector       `protobuf:"bytes,3,opt,name=pos,proto3" json:"pos,omitempty"`
	Vel                  *Vector       `protobuf:"bytes,4,opt,name=vel,proto3" json:"vel,omitempty"`
	Dna                  []byte        `protobuf:"bytes,5,opt,name=dna,proto3" json:"dna,omitempty"`
	Connections          []*Connection `protobuf:"bytes,6,rep,name=connections,proto3" json:"connections,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Cell) Reset()         { *m = Cell{} }
func (m *Cell) String() string { return proto.CompactTextString(m) }
func (*Cell) ProtoMessage()    {}
func (*Cell) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_6fd95a7833d73444, []int{2}
}
func (m *Cell) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cell.Unmarshal(m, b)
}
func (m *Cell) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cell.Marshal(b, m, deterministic)
}
func (dst *Cell) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cell.Merge(dst, src)
}
func (m *Cell) XXX_Size() int {
	return xxx_messageInfo_Cell.Size(m)
}
func (m *Cell) XXX_DiscardUnknown() {
	xxx_messageInfo_Cell.DiscardUnknown(m)
}

var xxx_messageInfo_Cell proto.InternalMessageInfo

func (m *Cell) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Cell) GetEnergyLevel() uint64 {
	if m != nil {
		return m.EnergyLevel
	}
	return 0
}

func (m *Cell) GetPos() *Vector {
	if m != nil {
		return m.Pos
	}
	return nil
}

func (m *Cell) GetVel() *Vector {
	if m != nil {
		return m.Vel
	}
	return nil
}

func (m *Cell) GetDna() []byte {
	if m != nil {
		return m.Dna
	}
	return nil
}

func (m *Cell) GetConnections() []*Connection {
	if m != nil {
		return m.Connections
	}
	return nil
}

type CellComputeBatch struct {
	TimeStep             uint64   `protobuf:"varint,1,opt,name=time_step,json=timeStep,proto3" json:"time_step,omitempty"`
	CellsToCompute       []*Cell  `protobuf:"bytes,2,rep,name=cells_to_compute,json=cellsToCompute,proto3" json:"cells_to_compute,omitempty"`
	CellsInProximity     []*Cell  `protobuf:"bytes,3,rep,name=cells_in_proximity,json=cellsInProximity,proto3" json:"cells_in_proximity,omitempty"`
	BatchKey             string   `protobuf:"bytes,4,opt,name=batch_key,json=batchKey,proto3" json:"batch_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CellComputeBatch) Reset()         { *m = CellComputeBatch{} }
func (m *CellComputeBatch) String() string { return proto.CompactTextString(m) }
func (*CellComputeBatch) ProtoMessage()    {}
func (*CellComputeBatch) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_6fd95a7833d73444, []int{3}
}
func (m *CellComputeBatch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CellComputeBatch.Unmarshal(m, b)
}
func (m *CellComputeBatch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CellComputeBatch.Marshal(b, m, deterministic)
}
func (dst *CellComputeBatch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CellComputeBatch.Merge(dst, src)
}
func (m *CellComputeBatch) XXX_Size() int {
	return xxx_messageInfo_CellComputeBatch.Size(m)
}
func (m *CellComputeBatch) XXX_DiscardUnknown() {
	xxx_messageInfo_CellComputeBatch.DiscardUnknown(m)
}

var xxx_messageInfo_CellComputeBatch proto.InternalMessageInfo

func (m *CellComputeBatch) GetTimeStep() uint64 {
	if m != nil {
		return m.TimeStep
	}
	return 0
}

func (m *CellComputeBatch) GetCellsToCompute() []*Cell {
	if m != nil {
		return m.CellsToCompute
	}
	return nil
}

func (m *CellComputeBatch) GetCellsInProximity() []*Cell {
	if m != nil {
		return m.CellsInProximity
	}
	return nil
}

func (m *CellComputeBatch) GetBatchKey() string {
	if m != nil {
		return m.BatchKey
	}
	return ""
}

type SpawnDimension struct {
	Start                *Vector  `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	End                  *Vector  `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SpawnDimension) Reset()         { *m = SpawnDimension{} }
func (m *SpawnDimension) String() string { return proto.CompactTextString(m) }
func (*SpawnDimension) ProtoMessage()    {}
func (*SpawnDimension) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_6fd95a7833d73444, []int{4}
}
func (m *SpawnDimension) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpawnDimension.Unmarshal(m, b)
}
func (m *SpawnDimension) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpawnDimension.Marshal(b, m, deterministic)
}
func (dst *SpawnDimension) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpawnDimension.Merge(dst, src)
}
func (m *SpawnDimension) XXX_Size() int {
	return xxx_messageInfo_SpawnDimension.Size(m)
}
func (m *SpawnDimension) XXX_DiscardUnknown() {
	xxx_messageInfo_SpawnDimension.DiscardUnknown(m)
}

var xxx_messageInfo_SpawnDimension proto.InternalMessageInfo

func (m *SpawnDimension) GetStart() *Vector {
	if m != nil {
		return m.Start
	}
	return nil
}

func (m *SpawnDimension) GetEnd() *Vector {
	if m != nil {
		return m.End
	}
	return nil
}

type DnaLengthRange struct {
	Min                  uint64   `protobuf:"varint,1,opt,name=min,proto3" json:"min,omitempty"`
	Max                  uint64   `protobuf:"varint,2,opt,name=max,proto3" json:"max,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DnaLengthRange) Reset()         { *m = DnaLengthRange{} }
func (m *DnaLengthRange) String() string { return proto.CompactTextString(m) }
func (*DnaLengthRange) ProtoMessage()    {}
func (*DnaLengthRange) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_6fd95a7833d73444, []int{5}
}
func (m *DnaLengthRange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DnaLengthRange.Unmarshal(m, b)
}
func (m *DnaLengthRange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DnaLengthRange.Marshal(b, m, deterministic)
}
func (dst *DnaLengthRange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DnaLengthRange.Merge(dst, src)
}
func (m *DnaLengthRange) XXX_Size() int {
	return xxx_messageInfo_DnaLengthRange.Size(m)
}
func (m *DnaLengthRange) XXX_DiscardUnknown() {
	xxx_messageInfo_DnaLengthRange.DiscardUnknown(m)
}

var xxx_messageInfo_DnaLengthRange proto.InternalMessageInfo

func (m *DnaLengthRange) GetMin() uint64 {
	if m != nil {
		return m.Min
	}
	return 0
}

func (m *DnaLengthRange) GetMax() uint64 {
	if m != nil {
		return m.Max
	}
	return 0
}

type BigBangRequest struct {
	SpawnDimension       *SpawnDimension `protobuf:"bytes,1,opt,name=spawn_dimension,json=spawnDimension,proto3" json:"spawn_dimension,omitempty"`
	EnergyLevel          uint64          `protobuf:"varint,2,opt,name=energy_level,json=energyLevel,proto3" json:"energy_level,omitempty"`
	CellAmount           uint64          `protobuf:"varint,3,opt,name=cell_amount,json=cellAmount,proto3" json:"cell_amount,omitempty"`
	DnaLengthRange       *DnaLengthRange `protobuf:"bytes,4,opt,name=dna_length_range,json=dnaLengthRange,proto3" json:"dna_length_range,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *BigBangRequest) Reset()         { *m = BigBangRequest{} }
func (m *BigBangRequest) String() string { return proto.CompactTextString(m) }
func (*BigBangRequest) ProtoMessage()    {}
func (*BigBangRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_6fd95a7833d73444, []int{6}
}
func (m *BigBangRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BigBangRequest.Unmarshal(m, b)
}
func (m *BigBangRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BigBangRequest.Marshal(b, m, deterministic)
}
func (dst *BigBangRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BigBangRequest.Merge(dst, src)
}
func (m *BigBangRequest) XXX_Size() int {
	return xxx_messageInfo_BigBangRequest.Size(m)
}
func (m *BigBangRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BigBangRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BigBangRequest proto.InternalMessageInfo

func (m *BigBangRequest) GetSpawnDimension() *SpawnDimension {
	if m != nil {
		return m.SpawnDimension
	}
	return nil
}

func (m *BigBangRequest) GetEnergyLevel() uint64 {
	if m != nil {
		return m.EnergyLevel
	}
	return 0
}

func (m *BigBangRequest) GetCellAmount() uint64 {
	if m != nil {
		return m.CellAmount
	}
	return 0
}

func (m *BigBangRequest) GetDnaLengthRange() *DnaLengthRange {
	if m != nil {
		return m.DnaLengthRange
	}
	return nil
}

type SlaveRegistration struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Threads              uint32   `protobuf:"varint,2,opt,name=threads,proto3" json:"threads,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SlaveRegistration) Reset()         { *m = SlaveRegistration{} }
func (m *SlaveRegistration) String() string { return proto.CompactTextString(m) }
func (*SlaveRegistration) ProtoMessage()    {}
func (*SlaveRegistration) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_6fd95a7833d73444, []int{7}
}
func (m *SlaveRegistration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SlaveRegistration.Unmarshal(m, b)
}
func (m *SlaveRegistration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SlaveRegistration.Marshal(b, m, deterministic)
}
func (dst *SlaveRegistration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SlaveRegistration.Merge(dst, src)
}
func (m *SlaveRegistration) XXX_Size() int {
	return xxx_messageInfo_SlaveRegistration.Size(m)
}
func (m *SlaveRegistration) XXX_DiscardUnknown() {
	xxx_messageInfo_SlaveRegistration.DiscardUnknown(m)
}

var xxx_messageInfo_SlaveRegistration proto.InternalMessageInfo

func (m *SlaveRegistration) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *SlaveRegistration) GetThreads() uint32 {
	if m != nil {
		return m.Threads
	}
	return 0
}

type SlaveRegistrationResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SlaveRegistrationResponse) Reset()         { *m = SlaveRegistrationResponse{} }
func (m *SlaveRegistrationResponse) String() string { return proto.CompactTextString(m) }
func (*SlaveRegistrationResponse) ProtoMessage()    {}
func (*SlaveRegistrationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_6fd95a7833d73444, []int{8}
}
func (m *SlaveRegistrationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SlaveRegistrationResponse.Unmarshal(m, b)
}
func (m *SlaveRegistrationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SlaveRegistrationResponse.Marshal(b, m, deterministic)
}
func (dst *SlaveRegistrationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SlaveRegistrationResponse.Merge(dst, src)
}
func (m *SlaveRegistrationResponse) XXX_Size() int {
	return xxx_messageInfo_SlaveRegistrationResponse.Size(m)
}
func (m *SlaveRegistrationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SlaveRegistrationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SlaveRegistrationResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Vector)(nil), "proto.Vector")
	proto.RegisterType((*Connection)(nil), "proto.Connection")
	proto.RegisterType((*Cell)(nil), "proto.Cell")
	proto.RegisterType((*CellComputeBatch)(nil), "proto.CellComputeBatch")
	proto.RegisterType((*SpawnDimension)(nil), "proto.SpawnDimension")
	proto.RegisterType((*DnaLengthRange)(nil), "proto.DnaLengthRange")
	proto.RegisterType((*BigBangRequest)(nil), "proto.BigBangRequest")
	proto.RegisterType((*SlaveRegistration)(nil), "proto.SlaveRegistration")
	proto.RegisterType((*SlaveRegistrationResponse)(nil), "proto.SlaveRegistrationResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CellInteractionServiceClient is the client API for CellInteractionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CellInteractionServiceClient interface {
	ComputeCellInteractions(ctx context.Context, in *CellComputeBatch, opts ...grpc.CallOption) (*CellComputeBatch, error)
	BigBang(ctx context.Context, in *BigBangRequest, opts ...grpc.CallOption) (CellInteractionService_BigBangClient, error)
}

type cellInteractionServiceClient struct {
	cc *grpc.ClientConn
}

func NewCellInteractionServiceClient(cc *grpc.ClientConn) CellInteractionServiceClient {
	return &cellInteractionServiceClient{cc}
}

func (c *cellInteractionServiceClient) ComputeCellInteractions(ctx context.Context, in *CellComputeBatch, opts ...grpc.CallOption) (*CellComputeBatch, error) {
	out := new(CellComputeBatch)
	err := c.cc.Invoke(ctx, "/proto.CellInteractionService/ComputeCellInteractions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cellInteractionServiceClient) BigBang(ctx context.Context, in *BigBangRequest, opts ...grpc.CallOption) (CellInteractionService_BigBangClient, error) {
	stream, err := c.cc.NewStream(ctx, &_CellInteractionService_serviceDesc.Streams[0], "/proto.CellInteractionService/BigBang", opts...)
	if err != nil {
		return nil, err
	}
	x := &cellInteractionServiceBigBangClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CellInteractionService_BigBangClient interface {
	Recv() (*Cell, error)
	grpc.ClientStream
}

type cellInteractionServiceBigBangClient struct {
	grpc.ClientStream
}

func (x *cellInteractionServiceBigBangClient) Recv() (*Cell, error) {
	m := new(Cell)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// CellInteractionServiceServer is the server API for CellInteractionService service.
type CellInteractionServiceServer interface {
	ComputeCellInteractions(context.Context, *CellComputeBatch) (*CellComputeBatch, error)
	BigBang(*BigBangRequest, CellInteractionService_BigBangServer) error
}

func RegisterCellInteractionServiceServer(s *grpc.Server, srv CellInteractionServiceServer) {
	s.RegisterService(&_CellInteractionService_serviceDesc, srv)
}

func _CellInteractionService_ComputeCellInteractions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CellComputeBatch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CellInteractionServiceServer).ComputeCellInteractions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.CellInteractionService/ComputeCellInteractions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CellInteractionServiceServer).ComputeCellInteractions(ctx, req.(*CellComputeBatch))
	}
	return interceptor(ctx, in, info, handler)
}

func _CellInteractionService_BigBang_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(BigBangRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CellInteractionServiceServer).BigBang(m, &cellInteractionServiceBigBangServer{stream})
}

type CellInteractionService_BigBangServer interface {
	Send(*Cell) error
	grpc.ServerStream
}

type cellInteractionServiceBigBangServer struct {
	grpc.ServerStream
}

func (x *cellInteractionServiceBigBangServer) Send(m *Cell) error {
	return x.ServerStream.SendMsg(m)
}

var _CellInteractionService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.CellInteractionService",
	HandlerType: (*CellInteractionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ComputeCellInteractions",
			Handler:    _CellInteractionService_ComputeCellInteractions_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "BigBang",
			Handler:       _CellInteractionService_BigBang_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "protocol.proto",
}

// SlaveRegistrationServiceClient is the client API for SlaveRegistrationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SlaveRegistrationServiceClient interface {
	Register(ctx context.Context, in *SlaveRegistration, opts ...grpc.CallOption) (*SlaveRegistrationResponse, error)
}

type slaveRegistrationServiceClient struct {
	cc *grpc.ClientConn
}

func NewSlaveRegistrationServiceClient(cc *grpc.ClientConn) SlaveRegistrationServiceClient {
	return &slaveRegistrationServiceClient{cc}
}

func (c *slaveRegistrationServiceClient) Register(ctx context.Context, in *SlaveRegistration, opts ...grpc.CallOption) (*SlaveRegistrationResponse, error) {
	out := new(SlaveRegistrationResponse)
	err := c.cc.Invoke(ctx, "/proto.SlaveRegistrationService/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SlaveRegistrationServiceServer is the server API for SlaveRegistrationService service.
type SlaveRegistrationServiceServer interface {
	Register(context.Context, *SlaveRegistration) (*SlaveRegistrationResponse, error)
}

func RegisterSlaveRegistrationServiceServer(s *grpc.Server, srv SlaveRegistrationServiceServer) {
	s.RegisterService(&_SlaveRegistrationService_serviceDesc, srv)
}

func _SlaveRegistrationService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SlaveRegistration)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SlaveRegistrationServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.SlaveRegistrationService/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SlaveRegistrationServiceServer).Register(ctx, req.(*SlaveRegistration))
	}
	return interceptor(ctx, in, info, handler)
}

var _SlaveRegistrationService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.SlaveRegistrationService",
	HandlerType: (*SlaveRegistrationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _SlaveRegistrationService_Register_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protocol.proto",
}

func init() { proto.RegisterFile("protocol.proto", fileDescriptor_protocol_6fd95a7833d73444) }

var fileDescriptor_protocol_6fd95a7833d73444 = []byte{
	// 609 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0xcd, 0x6e, 0xd3, 0x4c,
	0x14, 0x95, 0x93, 0xf4, 0xef, 0xa6, 0xf5, 0x97, 0x8e, 0xf4, 0x51, 0xd3, 0x2e, 0x08, 0x66, 0xd3,
	0x55, 0x8b, 0x52, 0x58, 0xb0, 0x01, 0xd1, 0x56, 0xa0, 0xaa, 0x5d, 0xa0, 0x49, 0xd5, 0xad, 0x35,
	0xf5, 0x5c, 0xa5, 0x23, 0x9c, 0x19, 0x33, 0x33, 0x2d, 0x71, 0x1f, 0x84, 0xc7, 0x61, 0xc1, 0x3b,
	0xf0, 0x3e, 0xe8, 0x8e, 0x6d, 0x48, 0x1a, 0x2a, 0xb1, 0xf2, 0xdc, 0xff, 0x73, 0xee, 0x3d, 0x86,
	0xb8, 0xb4, 0xc6, 0x9b, 0xdc, 0x14, 0x07, 0xe1, 0xc1, 0x56, 0xc2, 0x27, 0x1d, 0xc1, 0xea, 0x15,
	0xe6, 0xde, 0x58, 0xb6, 0x09, 0xd1, 0x2c, 0x89, 0x86, 0xd1, 0x7e, 0x87, 0x47, 0x33, 0xb2, 0xaa,
	0xa4, 0x53, 0x5b, 0x15, 0x59, 0xf7, 0x49, 0xb7, 0xb6, 0xee, 0xd3, 0x43, 0x80, 0x13, 0xa3, 0x35,
	0xe6, 0x5e, 0x19, 0xcd, 0x9e, 0xc3, 0x66, 0x5e, 0x5b, 0x28, 0x33, 0x6f, 0x42, 0x8b, 0x0d, 0xde,
	0xff, 0xed, 0xbb, 0x34, 0xe9, 0x8f, 0x08, 0x7a, 0x27, 0x58, 0x14, 0x2c, 0x86, 0x8e, 0x92, 0x4d,
	0x46, 0x47, 0x49, 0xaa, 0x45, 0x8d, 0x76, 0x52, 0x65, 0x05, 0xde, 0x61, 0x11, 0x06, 0xf6, 0x78,
	0xbf, 0xf6, 0x5d, 0x90, 0x8b, 0x3d, 0x83, 0x6e, 0x69, 0x5c, 0x18, 0xde, 0x1f, 0x6d, 0xd5, 0xe0,
	0x0f, 0x6a, 0xc8, 0x9c, 0x22, 0x94, 0x40, 0xa5, 0xbd, 0xbf, 0x26, 0x50, 0x87, 0x01, 0x74, 0xa5,
	0x16, 0xc9, 0xca, 0x30, 0xda, 0xdf, 0xe4, 0xf4, 0x64, 0x47, 0xd0, 0xc2, 0x53, 0x46, 0xbb, 0x64,
	0x75, 0xd8, 0xdd, 0xef, 0x8f, 0xb6, 0x9b, 0xd2, 0x3f, 0xd4, 0xf8, 0x7c, 0x56, 0xfa, 0x3d, 0x82,
	0x01, 0x91, 0x38, 0x31, 0xd3, 0xf2, 0xd6, 0xe3, 0xb1, 0xf0, 0xf9, 0x0d, 0xdb, 0x83, 0x0d, 0xaf,
	0xa6, 0x98, 0x39, 0x8f, 0x65, 0xe0, 0xd5, 0xe3, 0xeb, 0xe4, 0x18, 0x7b, 0x2c, 0xd9, 0x6b, 0x18,
	0xe4, 0x58, 0x14, 0x2e, 0xf3, 0x26, 0xcb, 0xeb, 0xaa, 0xa4, 0x13, 0x66, 0xf5, 0xdb, 0x59, 0x58,
	0x14, 0x3c, 0x0e, 0x49, 0x97, 0xa6, 0x69, 0xcc, 0xde, 0x00, 0xab, 0xcb, 0x94, 0xce, 0x4a, 0x6b,
	0x66, 0x6a, 0xaa, 0x7c, 0x95, 0x74, 0x97, 0x0b, 0xeb, 0xee, 0x67, 0xfa, 0x53, 0x9b, 0x44, 0x70,
	0xae, 0x09, 0x57, 0xf6, 0x19, 0xab, 0xb0, 0x91, 0x0d, 0xbe, 0x1e, 0x1c, 0xe7, 0x58, 0xa5, 0x57,
	0x10, 0x8f, 0x4b, 0xf1, 0x55, 0x9f, 0xaa, 0x29, 0x6a, 0x47, 0xa7, 0x7b, 0x01, 0x2b, 0xce, 0x0b,
	0xeb, 0x03, 0xf2, 0xa5, 0xe5, 0xd5, 0x31, 0xda, 0x2f, 0x6a, 0x19, 0x4e, 0xb3, 0xbc, 0x5f, 0xd4,
	0x32, 0x7d, 0x05, 0xf1, 0xa9, 0x16, 0x17, 0xa8, 0x27, 0xfe, 0x86, 0x0b, 0x3d, 0x41, 0xda, 0xf8,
	0x54, 0xe9, 0x66, 0x1f, 0xf4, 0x0c, 0x1e, 0x31, 0x6b, 0xee, 0x4b, 0xcf, 0xf4, 0x67, 0x04, 0xf1,
	0xb1, 0x9a, 0x1c, 0x0b, 0x3d, 0xe1, 0xf8, 0xe5, 0x16, 0x9d, 0x67, 0x6f, 0xe1, 0x3f, 0x47, 0x00,
	0x33, 0xd9, 0x22, 0x6c, 0x80, 0xfd, 0xdf, 0x4c, 0x5d, 0x84, 0xcf, 0x63, 0xb7, 0x48, 0xe7, 0x9f,
	0xd4, 0xd4, 0xa7, 0xa5, 0x65, 0x62, 0x6a, 0x6e, 0xb5, 0x0f, 0xaa, 0xea, 0x71, 0x20, 0xd7, 0xfb,
	0xe0, 0x61, 0xef, 0x60, 0x20, 0xb5, 0xc8, 0x8a, 0xc0, 0x26, 0xb3, 0x44, 0xa7, 0x91, 0x56, 0x0b,
	0x62, 0x91, 0x2b, 0x8f, 0xe5, 0x82, 0x9d, 0x7e, 0x84, 0xed, 0x71, 0x21, 0xee, 0x90, 0xe3, 0x44,
	0x39, 0x6f, 0x45, 0xf8, 0x47, 0x12, 0x58, 0x13, 0x52, 0x5a, 0x74, 0xae, 0x11, 0x7f, 0x6b, 0x52,
	0xc4, 0xdf, 0x58, 0x14, 0xd2, 0x05, 0xb8, 0x5b, 0xbc, 0x35, 0xd3, 0x3d, 0x78, 0xba, 0xd4, 0x88,
	0xa3, 0x2b, 0x8d, 0x76, 0x38, 0xfa, 0x16, 0xc1, 0x13, 0xd2, 0xc0, 0x99, 0xf6, 0x68, 0x45, 0x50,
	0xe8, 0x18, 0xed, 0x9d, 0xca, 0x91, 0x9d, 0xc3, 0x4e, 0xa3, 0xa4, 0x07, 0x09, 0x8e, 0xed, 0xcc,
	0xa9, 0x67, 0x5e, 0xc6, 0xbb, 0x8f, 0x05, 0xd8, 0x21, 0xac, 0x35, 0x47, 0x62, 0x2d, 0xff, 0xc5,
	0xa3, 0xed, 0xce, 0x2b, 0xf2, 0x65, 0x34, 0xba, 0x86, 0x64, 0x09, 0x75, 0x8b, 0xec, 0x03, 0xac,
	0xd7, 0x6e, 0xb4, 0x2c, 0x69, 0x4f, 0xfa, 0x30, 0x79, 0x77, 0xf8, 0x58, 0xa4, 0x25, 0x7f, 0xbd,
	0x1a, 0x12, 0x8e, 0x7e, 0x05, 0x00, 0x00, 0xff, 0xff, 0xc3, 0xdc, 0xc1, 0x86, 0xd3, 0x04, 0x00,
	0x00,
}
